language: minimal

services: docker

before_install:
  - docker -v && docker-compose -v
  
install:
  - docker-compose -f deployment/docker/docker-compose-build.yaml build --parallel
  
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose -f deployment/docker/docker-compose-build.yaml push
