version: "2"
services:
  reverseproxy:
    build:
      context: .
    image: vicatar/reverseproxy 
  backend_user:
    build:
      context: ../../user
    image: vicatar/udacity-restapi-user
  backend_feed:
    build:
      context: ../../feed  
    image: vicatar/udacity-restapi-feed
  frontend:
    build:
      context: ../../frontend  
    image: vicatar/udacity-frontend:local
